### ISSUE TITLE
[Todo-List작성] / 프로젝트에 필요한 Todo-List를 Requirements 별로 나누어 작성.

### ISSUE THREAD

**Issue by hanulhanul** [codestates-beb/BEB-06-FIRST-08#1]
### Bare Minimum (필수)

* 헤더 생성 
- [x] #3
- [x] #4
- [x] 지갑 연결 버튼
  - [ ] 지갑 연결을 했을 때, 지갑 연결이 되어 있는 상태를 표시할 수 있는 로고
  - [ ] 지갑 연결을 하지 않았을 때, 지갑 연결되어 있지 않는 상태를 표시할 수 있는 로고
 - [x] 마켓, NFT민팅, 마이페이지 내비게이션
* 메인 페이지 (랜딩 페이지)
   *  NFT Section (Header 바로 아래 부분)
      - [x] NFT Section의 배경 구현.
   *  NFT 리스트
     - [x] 게시글 제목에 커서를 대면 커서가 누르는 모양으로 바뀌어야 함
     - [x] #9
     - [x] #11
     - [x] 서버에서 받아온 데이터로, 4행 3열 image와 holder, value 를 나타내야함.
* 스키마 및 API
  - [x] ERD (DB Diagram) 작성.

### Recommended (권장)
* 메인 페이지 (렌딩 페이지)
   *  NFT 리스트
     - [ ] 5페이지까지 페이지네이션으로 구현.
* NFT 민팅 페이지
   - [ ] 리액트에서 제공하는 기본 폼으로 NFT 민팅 페이지를 개발
   - [ ] 이미지, 이름, 상세내용 칸 있어야 함
   - [ ] 민팅 버튼을 누르면, 지갑 서명 통해 트랜잭션 수행해야 함
* 테마별 NFT 리스트 페이지
  - [ ] 탭 기능 사용하여 테마별 NFT 리스트 조회 가능해야 함
  - [ ] NFT 이미지와 작가 이름 존재해야 함
  - [ ] 목록 버튼을 누르면 게시글 리스트의 클릭했던 목록으로 돌아감
* 스키마 및 API
  - [ ] API 작성 툴 (Gitbook API) 같이 고민해보기.

### Advanced (도전해볼만 합니다)
* 메인 페이지 (렌딩 페이지)
  * NFT Section
    - [ ] 일정 시간 간격으로, 리스트가 바뀌는 기능.
    - [ ] 마우스를 올렸을때, 리스트가 변하는건 멈춰야 함.
    - [ ] >, < 버튼 구현
* NFT 상세 페이지
 - [ ] 이미지를 포함한 NFT 상세 정보를 보여줄 수 있어야 함
 - [ ] 거래되는 가격을 보여줄 수 있어야함
 - [ ] 구입버튼을 누르면 지갑을 통해 트랜잭션을 수행할 수 있어야 함
* 마이 페이지
- [ ] 프로필, 보유한 NFT, 발행한 NFT 를 볼 수 있어야 함
- [ ] 지갑 연결을 해제할 수 있어야함

### Nightmare (신중히 결정하세요)
* 메인 페이지 (렌딩 페이지)
  * NFT Section
    - [ ] 마우스를 올렸을때, 리스트가 변하는건 멈춰야 함.
    - [ ] >, < 버튼 구현
